server:
  port: 8700

spring:
  application:
    name: sb_rabbitmq
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: admin
    password: admin

  cloud:
    stream:
      function:
        definition: MyMessageListener
      bindings:
        MyMessageListener-in-0:
          destination: myMessageExchange
          group: myMessageQueue