server:
  port: 8701

spring:
  application:
    name: sb_rabbitmq
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: admin
    password: admin

  cloud:
    stream:
      function:
        definition: demoMyMessageListener;demoMyMessageListenerString;demoMyMessageListenerLong;
      bindings:
        demoMyMessageListener-in-0:
          destination: demomyMessageExchange
          group: demomyMessageQueue
        demoMyMessageListenerString-in-0:
          destination: demomyMessageExchangeString
          group: demomyMessageQueueString
        demoMyMessageListenerLong-in-0:
          destination: demomyMessageExchangeLong
          group: demomyMessageQueueLong