
server:
  port: 9200

spring:
  application:
    name: consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      enabled: true
      discovery:
        register: true
        enabled: true
#        prefer-ip-address: true
        heartbeat:
          enabled: true
          ttl-value: 30
          ttl-unit: s
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}

#debug: true
