server:
  port: 7500

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://tx-gd:4409/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: nacos
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/com/cz/spring_boot_test/dao/*Mapper.xml