---
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0.0.0.0"
elasticsearch.url: http://192.168.20.19:9200/
xpack.monitoring.ui.container.elasticsearch.enabled: true
