server:
    port: 8621


spring:
    servlet:
      multipart:
          max-file-size: 1000MB
          max-request-size: 1000MB
    minio:
        enabled: true
        key: aaaacccc
        secret: aaaacccc
        url: http://192.168.18.251:9000 # 此处需要填写api端口
        bucket: test
    aliyun:
        enabled: false

fdfs:
    connect-timeout: 500
    tracker-list:
        - 192.168.18.101:22122

