server:
    port: 8621


spring:
    servlet:
      multipart:
          max-file-size: 1000MB
          max-request-size: 1000MB
    minio:
        enabled: false
        key: minio
        secret: Alian123
        url: http://tx-gd:19001 # 此处需要填写api端口
        bucket: spring-boot-minio-bucket

fdfs:
    connect-timeout: 500
    tracker-list:
        - 192.168.18.101:22122

