server:
  port: 18104

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    host: tx-gd
    port: 6379
    connect-timeout: 1000

test:
  cron: 0/5 * * * * ?

#config_test_in_yml: ${config_test}


my:
  ds:
    key1: v1
    key2: v22

config:
  msg: hello world!