server:
  port: 11999

spring:
  application:
    name: oauth-server

  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        heartbeat:
          ttl-value: 30
          ttl-unit: s
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
  datasource:
    url: jdbc:mysql://tx-gd:4409/oauth2
    username: nacos
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      max-wait: 10000
