server:
  port: 8701

spring:
  application:
    name: sb_rabbitmq
  rabbitmq:
    virtual-host: /
    host: 106.53.96.154
    port: 5673
    username: admin
    password: admin
    publisher-confirm-type: correlated
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: true # 重试超过最大次数之后是否拒绝
        retry:
          enabled: true # 开启重试
          max-attempts: 5 # 发送失败最多重试5次
          initial-interval: 500ms # 重试间隔
        prefetch: 5


  cloud:
    stream:
      function:
        definition: demoMyMessageListener;demoMyMessageListenerString;demoMyMessageListenerLong;
      bindings:
        demoMyMessageListener-in-0:
          destination: demomyMessageExchange
          group: demomyMessageQueue
        demoMyMessageListenerString-in-0:
          destination: demomyMessageExchangeString
          group: demomyMessageQueueString
        demoMyMessageListenerLong-in-0:
          destination: demomyMessageExchangeLong
          group: demomyMessageQueueLong