server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://tx-gd:3306/security
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  security:
    user:
      name: admin1
      password: admin1
      roles:
        - admin

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl