server:
  port: 9203

spring:
  application:
    name: consumer_feign_hystrix
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      enabled: true # 是否启用consul
      discovery:
        register: false # 是否注册到consul
        enabled: true # 是否启用服务发现
        prefer-ip-address: true # 注册到consul是否使用ip
        heartbeat: # 心跳
          enabled: true
          ttl-value: 30
          ttl-unit: s
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}

# 暴露所有actuator端点
management:
  endpoint:
    web:
      expose:
        include: "*"
    health:
      show-details: always

# actuator info端点暴露的数据
info:
  app:
    name: @project.artifactId@

# 回退方法的三种方式, 只能将一种属性设置为true,否则启动容器失败
method: false  # 使用@HystrixCommand注解饿fallbackmethod属性开启回退方法
prop: false  # 使用@FeignClient的fallback属性开启回退方法
factory: true  # 使用@FeignClient的fallbackfactory属性开启回退方法

# 打开feign客户端的断路器,否则@FeignClient的fallback属性无效
feign:
  hystrix:
    enabled: true
