server:
  port: 8600

spring:
  application:
    name: mybatis
  datasource:
    url: jdbc:mysql://tx-gd:4409/test?useUnicode=true&amp;characeterEncoding=utf-8&amp;serverTimezone=UTC&amp;useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: nacos
    password: 123456

mybatis:
  mapper-location: classpath:com/cz/springbootmybatissourcecode/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
