server:
  port: 8600

spring:
  application:
    name: mybatis
  datasource:
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&amp;characeterEncoding=utf-8&amp;serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-location: classpath:com/cz/springbootmybatissourcecode/mapper/*.xml
