
server:
  port: 8900

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  config: classpath:config/logback-spring.xml

mybatis-plus:
  mapper-locations: classpath:com/cz/elk/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
