server:
  port: 11192
  jetty:
    threads:
      idle-timeout: 10000ms
  tomcat:
    connection-timeout: 20000ms


spring:
  redis:
    timeout: 10000ms
    host: tx-sh
    port: 17777
  cache:
    type: REDIS

