server:
  port: ${random.int[9120,9125]}

spring:
  application:
    name: user
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        heartbeat:
          ttl-value: 30
          ttl-unit: s
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  config: classpath:config/logback-spring.xml
