server:
  port: 8699

spring:
  datasource:
    dynamic:
      primary: ds1
      strict: false
      datasource:
        ds1:
          url: jdbc:mysql://tx-gd:4409/t?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: nacos
          password: 123456
        ds2:
          url: jdbc:mysql://tx-gd:4409/t?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: nacos
          password: 123456
#logging:
#  level:
#    root: debug

mybatis-plus:
  type-handlers-package: com.cz.spring_boot_mybatis_dynamic_ds.typehandler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
