server:
  port: 9100

spring:
  application:
    name: provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        heartbeat:
          enabled: true
          ttl-value: 30
          ttl-unit: s
        preferIpAddress: true
        health-check-path: /health
        health-check-interval: 15s
        instance-id: ${spring.application.name}
        ip-address: 192.168.20.19