server:
  port: 8761

rocketmq:
  name-server: localhost:9876
  producer:
    group: JzmGroup
    send-message-timeout: 1000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.53.96.154:4409/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
    username: nacos
    password: 123456

mybatis-plus:
  mapper-locations: classpath:com/cz/rocket/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl