server:
  port: 9202

spring:
  application:
    name: consumer_feign
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        register: false
        prefer-ip-address: true
        heartbeat:
          enabled: true
          ttl-value: 30
          ttl-unit: s
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
